var data = [
{
  Name: "Igor Arinichev",
  Discipline: "Analysis",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Igor Arinichev",
  Discipline: "Algebra",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Igor Arinichev",
  Discipline: "Geometry",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Igor Arinichev",
  Discipline: "Differential Equations",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Igor Arinichev",
  Discipline: "Topology",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Igor Arinichev",
  Discipline: "Irish Dance",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Igor Arinichev",
  Discipline: "Economics",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Igor Arinichev",
  Discipline: "Geography",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Igor Arinichev",
  Discipline: "Paleontology",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Igor Arinichev",
  Discipline: "History",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Igor Arinichev",
  Discipline: "Biology",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Igor Arinichev",
  Discipline: "Algebraic Topology",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Igor Arinichev",
  Discipline: "Computer Sciences",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Igor Arinichev",
  Discipline: "Introduction to shiting",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Igor Arinichev",
  Discipline: "Introduction to pissing",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Igor Arinichev",
  Discipline: "Shiting (advanced level)",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Igor Arinichev",
  Discipline: "Pissing (advanced level)",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Igor Arinichev",
  Discipline: "Speaking like a man",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Igor Arinichev",
  Discipline: "Catching squirrels",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Igor Arinichev",
  Discipline: "Stealing money at streets",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Igor Arinichev",
  Discipline: "Leaving in Ismailovo",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Igor Arinichev",
  Discipline: "Krasnodaring",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Sergey Polyanskikh",
  Discipline: "Analysis",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Sergey Polyanskikh",
  Discipline: "Algebra",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Sergey Polyanskikh",
  Discipline: "Geometry",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Sergey Polyanskikh",
  Discipline: "Differential Equations",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Sergey Polyanskikh",
  Discipline: "Economics",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Sergey Polyanskikh",
  Discipline: "English",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Sergey Polyanskikh",
  Discipline: "Russian",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Sergey Polyanskikh",
  Discipline: "Art",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Sergey Polyanskikh",
  Discipline: "Geography",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Sergey Polyanskikh",
  Discipline: "Biology",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Sergey Polyanskikh",
  Discipline: "Algebraic Topology",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Sergey Polyanskikh",
  Discipline: "Tekhnical Analysis",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Sergey Polyanskikh",
  Discipline: "Introduction to shiting",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Sergey Polyanskikh",
  Discipline: "Introduction to pissing",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Sergey Polyanskikh",
  Discipline: "Shiting (advanced level)",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Sergey Polyanskikh",
  Discipline: "Pissing (advanced level)",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Sergey Polyanskikh",
  Discipline: "Speaking like a man",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Sergey Polyanskikh",
  Discipline: "Street fighting",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Sergey Polyanskikh",
  Discipline: "Catching squirrels",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Sergey Polyanskikh",
  Discipline: "Stealing money at parks",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Sergey Davidenko",
  Discipline: "Analysis",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Sergey Davidenko",
  Discipline: "Geometry",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Sergey Davidenko",
  Discipline: "Differential Equations",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Sergey Davidenko",
  Discipline: "Irish Dance",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Sergey Davidenko",
  Discipline: "Economics",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Sergey Davidenko",
  Discipline: "English",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Sergey Davidenko",
  Discipline: "Russian",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Sergey Davidenko",
  Discipline: "Art",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Sergey Davidenko",
  Discipline: "Geography",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Sergey Davidenko",
  Discipline: "Paleontology",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Sergey Davidenko",
  Discipline: "Algebraic Topology",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Sergey Davidenko",
  Discipline: "Tekhnical Analysis",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Sergey Davidenko",
  Discipline: "Introduction to shiting",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Sergey Davidenko",
  Discipline: "Introduction to pissing",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Sergey Davidenko",
  Discipline: "Shiting (advanced level)",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Sergey Davidenko",
  Discipline: "Pissing (advanced level)",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Sergey Davidenko",
  Discipline: "Speaking like a man",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Sergey Davidenko",
  Discipline: "Street fighting",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Sergey Davidenko",
  Discipline: "Catching squirrels",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Sergey Davidenko",
  Discipline: "Stealing money at parks",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Sergey Davidenko",
  Discipline: "Stealing money at streets",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Sergey Davidenko",
  Discipline: "Leaving in Ismailovo",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Mikhail Lagoyda",
  Discipline: "Analysis",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Mikhail Lagoyda",
  Discipline: "Algebra",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Mikhail Lagoyda",
  Discipline: "Geometry",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Mikhail Lagoyda",
  Discipline: "Differential Equations",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Mikhail Lagoyda",
  Discipline: "Topology",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Mikhail Lagoyda",
  Discipline: "Economics",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Mikhail Lagoyda",
  Discipline: "English",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Mikhail Lagoyda",
  Discipline: "Art",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Mikhail Lagoyda",
  Discipline: "Geography",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Mikhail Lagoyda",
  Discipline: "Paleontology",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Mikhail Lagoyda",
  Discipline: "History",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Mikhail Lagoyda",
  Discipline: "Biology",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Mikhail Lagoyda",
  Discipline: "Algebraic Topology",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Mikhail Lagoyda",
  Discipline: "Tekhnical Analysis",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Mikhail Lagoyda",
  Discipline: "Introduction to shiting",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Mikhail Lagoyda",
  Discipline: "Shiting (advanced level)",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Mikhail Lagoyda",
  Discipline: "Pissing (advanced level)",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Mikhail Lagoyda",
  Discipline: "Speaking like a man",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Mikhail Lagoyda",
  Discipline: "Stealing money at parks",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Mikhail Lagoyda",
  Discipline: "Stealing money at streets",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Mikhail Lagoyda",
  Discipline: "Leaving in Ismailovo",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Mikhail Lagoyda",
  Discipline: "Krasnodaring",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Zinovy Tsalyuk",
  Discipline: "Analysis",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Zinovy Tsalyuk",
  Discipline: "Geometry",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Zinovy Tsalyuk",
  Discipline: "Differential Equations",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Zinovy Tsalyuk",
  Discipline: "Topology",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Zinovy Tsalyuk",
  Discipline: "Economics",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Zinovy Tsalyuk",
  Discipline: "English",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Zinovy Tsalyuk",
  Discipline: "Art",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Zinovy Tsalyuk",
  Discipline: "Geography",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Zinovy Tsalyuk",
  Discipline: "History",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Zinovy Tsalyuk",
  Discipline: "Biology",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Zinovy Tsalyuk",
  Discipline: "Algebraic Topology",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Zinovy Tsalyuk",
  Discipline: "Computer Sciences",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Zinovy Tsalyuk",
  Discipline: "Tekhnical Analysis",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Zinovy Tsalyuk",
  Discipline: "Introduction to pissing",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Zinovy Tsalyuk",
  Discipline: "Shiting (advanced level)",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Zinovy Tsalyuk",
  Discipline: "Street fighting",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Zinovy Tsalyuk",
  Discipline: "Catching squirrels",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Zinovy Tsalyuk",
  Discipline: "Stealing money at parks",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Zinovy Tsalyuk",
  Discipline: "Leaving in Ismailovo",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Zinovy Tsalyuk",
  Discipline: "Krasnodaring",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Vasily Pulyaev",
  Discipline: "Analysis",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Vasily Pulyaev",
  Discipline: "Algebra",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Vasily Pulyaev",
  Discipline: "Geometry",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Vasily Pulyaev",
  Discipline: "Topology",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Vasily Pulyaev",
  Discipline: "Economics",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Vasily Pulyaev",
  Discipline: "Russian",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Vasily Pulyaev",
  Discipline: "Art",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Vasily Pulyaev",
  Discipline: "Paleontology",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Vasily Pulyaev",
  Discipline: "History",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Vasily Pulyaev",
  Discipline: "Biology",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Vasily Pulyaev",
  Discipline: "Algebraic Topology",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Vasily Pulyaev",
  Discipline: "Tekhnical Analysis",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Vasily Pulyaev",
  Discipline: "Pissing (advanced level)",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Vasily Pulyaev",
  Discipline: "Street fighting",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Vasily Pulyaev",
  Discipline: "Catching squirrels",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Vasily Pulyaev",
  Discipline: "Stealing money at parks",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Vasily Pulyaev",
  Discipline: "Stealing money at streets",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Vasily Pulyaev",
  Discipline: "Leaving in Ismailovo",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Vasily Pulyaev",
  Discipline: "Krasnodaring",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Alex Skryago",
  Discipline: "Analysis",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Alex Skryago",
  Discipline: "Algebra",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Alex Skryago",
  Discipline: "Geometry",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Alex Skryago",
  Discipline: "Differential Equations",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Alex Skryago",
  Discipline: "Topology",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Alex Skryago",
  Discipline: "Irish Dance",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Alex Skryago",
  Discipline: "Economics",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Alex Skryago",
  Discipline: "English",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Alex Skryago",
  Discipline: "Russian",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Alex Skryago",
  Discipline: "Art",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Alex Skryago",
  Discipline: "Geography",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Alex Skryago",
  Discipline: "Paleontology",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Alex Skryago",
  Discipline: "History",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Alex Skryago",
  Discipline: "Biology",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Alex Skryago",
  Discipline: "Algebraic Topology",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Alex Skryago",
  Discipline: "Tekhnical Analysis",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Alex Skryago",
  Discipline: "Introduction to shiting",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Alex Skryago",
  Discipline: "Introduction to pissing",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Alex Skryago",
  Discipline: "Shiting (advanced level)",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Alex Skryago",
  Discipline: "Pissing (advanced level)",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Alex Skryago",
  Discipline: "Speaking like a man",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Alex Skryago",
  Discipline: "Catching squirrels",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Alex Skryago",
  Discipline: "Leaving in Ismailovo",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Jenya Scherbakov",
  Discipline: "Analysis",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Jenya Scherbakov",
  Discipline: "Algebra",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Jenya Scherbakov",
  Discipline: "Geometry",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Jenya Scherbakov",
  Discipline: "Differential Equations",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Jenya Scherbakov",
  Discipline: "Topology",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Jenya Scherbakov",
  Discipline: "Irish Dance",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Jenya Scherbakov",
  Discipline: "Economics",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Jenya Scherbakov",
  Discipline: "English",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Jenya Scherbakov",
  Discipline: "Russian",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Jenya Scherbakov",
  Discipline: "Art",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Jenya Scherbakov",
  Discipline: "Geography",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Jenya Scherbakov",
  Discipline: "Paleontology",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Jenya Scherbakov",
  Discipline: "History",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Jenya Scherbakov",
  Discipline: "Algebraic Topology",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Jenya Scherbakov",
  Discipline: "Computer Sciences",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Jenya Scherbakov",
  Discipline: "Tekhnical Analysis",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Jenya Scherbakov",
  Discipline: "Introduction to shiting",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Jenya Scherbakov",
  Discipline: "Introduction to pissing",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Jenya Scherbakov",
  Discipline: "Pissing (advanced level)",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Jenya Scherbakov",
  Discipline: "Street fighting",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Jenya Scherbakov",
  Discipline: "Leaving in Ismailovo",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Anjella Jolie",
  Discipline: "Algebra",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Anjella Jolie",
  Discipline: "Geometry",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Anjella Jolie",
  Discipline: "Differential Equations",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Anjella Jolie",
  Discipline: "Topology",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Anjella Jolie",
  Discipline: "Economics",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Anjella Jolie",
  Discipline: "English",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Anjella Jolie",
  Discipline: "Art",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Anjella Jolie",
  Discipline: "Geography",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Anjella Jolie",
  Discipline: "Algebraic Topology",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Anjella Jolie",
  Discipline: "Computer Sciences",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Anjella Jolie",
  Discipline: "Introduction to pissing",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Anjella Jolie",
  Discipline: "Pissing (advanced level)",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Anjella Jolie",
  Discipline: "Street fighting",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Anjella Jolie",
  Discipline: "Catching squirrels",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Anjella Jolie",
  Discipline: "Stealing money at parks",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Anjella Jolie",
  Discipline: "Stealing money at streets",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Anjella Jolie",
  Discipline: "Leaving in Ismailovo",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Anjella Jolie",
  Discipline: "Krasnodaring",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Anna",
  Discipline: "Analysis",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Anna",
  Discipline: "Geometry",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Anna",
  Discipline: "Differential Equations",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Anna",
  Discipline: "Topology",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Anna",
  Discipline: "Irish Dance",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Anna",
  Discipline: "Art",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Anna",
  Discipline: "Geography",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Anna",
  Discipline: "History",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Anna",
  Discipline: "Algebraic Topology",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Anna",
  Discipline: "Tekhnical Analysis",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Anna",
  Discipline: "Introduction to shiting",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Anna",
  Discipline: "Introduction to pissing",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Anna",
  Discipline: "Pissing (advanced level)",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Anna",
  Discipline: "Catching squirrels",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Anna",
  Discipline: "Stealing money at streets",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Helen",
  Discipline: "Analysis",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Helen",
  Discipline: "Algebra",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Helen",
  Discipline: "Geometry",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Helen",
  Discipline: "Differential Equations",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Helen",
  Discipline: "Russian",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Helen",
  Discipline: "Geography",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Helen",
  Discipline: "Paleontology",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Helen",
  Discipline: "History",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Helen",
  Discipline: "Biology",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Helen",
  Discipline: "Computer Sciences",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Helen",
  Discipline: "Tekhnical Analysis",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Helen",
  Discipline: "Introduction to shiting",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Helen",
  Discipline: "Introduction to pissing",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Helen",
  Discipline: "Shiting (advanced level)",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Helen",
  Discipline: "Pissing (advanced level)",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Helen",
  Discipline: "Street fighting",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Helen",
  Discipline: "Catching squirrels",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Helen",
  Discipline: "Stealing money at streets",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Helen",
  Discipline: "Leaving in Ismailovo",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Berta",
  Discipline: "Algebra",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Berta",
  Discipline: "Geometry",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Berta",
  Discipline: "Differential Equations",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Berta",
  Discipline: "Art",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Berta",
  Discipline: "Geography",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Berta",
  Discipline: "Biology",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Berta",
  Discipline: "Computer Sciences",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Berta",
  Discipline: "Introduction to shiting",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Berta",
  Discipline: "Pissing (advanced level)",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Berta",
  Discipline: "Speaking like a man",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Berta",
  Discipline: "Street fighting",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Berta",
  Discipline: "Catching squirrels",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Berta",
  Discipline: "Stealing money at parks",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Berta",
  Discipline: "Stealing money at streets",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Berta",
  Discipline: "Krasnodaring",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Margery",
  Discipline: "Analysis",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Margery",
  Discipline: "Algebra",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Margery",
  Discipline: "Geometry",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Margery",
  Discipline: "Differential Equations",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Margery",
  Discipline: "Irish Dance",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Margery",
  Discipline: "Russian",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Margery",
  Discipline: "Art",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Margery",
  Discipline: "Geography",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Margery",
  Discipline: "Paleontology",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Margery",
  Discipline: "Computer Sciences",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Margery",
  Discipline: "Tekhnical Analysis",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Margery",
  Discipline: "Introduction to shiting",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Margery",
  Discipline: "Introduction to pissing",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Margery",
  Discipline: "Pissing (advanced level)",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Margery",
  Discipline: "Speaking like a man",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Margery",
  Discipline: "Street fighting",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Margery",
  Discipline: "Catching squirrels",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Margery",
  Discipline: "Stealing money at parks",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Margery",
  Discipline: "Stealing money at streets",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Margery",
  Discipline: "Leaving in Ismailovo",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Margery",
  Discipline: "Krasnodaring",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Nick",
  Discipline: "Algebra",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Nick",
  Discipline: "Geometry",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Nick",
  Discipline: "Differential Equations",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Nick",
  Discipline: "Topology",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Nick",
  Discipline: "Irish Dance",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Nick",
  Discipline: "Economics",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Nick",
  Discipline: "English",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Nick",
  Discipline: "Art",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Nick",
  Discipline: "Geography",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Nick",
  Discipline: "History",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Nick",
  Discipline: "Biology",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Nick",
  Discipline: "Algebraic Topology",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Nick",
  Discipline: "Introduction to shiting",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Nick",
  Discipline: "Shiting (advanced level)",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Nick",
  Discipline: "Pissing (advanced level)",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Nick",
  Discipline: "Street fighting",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Nick",
  Discipline: "Leaving in Ismailovo",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Nick",
  Discipline: "Krasnodaring",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Vitaly",
  Discipline: "Analysis",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Vitaly",
  Discipline: "Algebra",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Vitaly",
  Discipline: "Geometry",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Vitaly",
  Discipline: "Differential Equations",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Vitaly",
  Discipline: "Topology",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Vitaly",
  Discipline: "Irish Dance",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Vitaly",
  Discipline: "English",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Vitaly",
  Discipline: "Russian",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Vitaly",
  Discipline: "Geography",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Vitaly",
  Discipline: "Paleontology",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Vitaly",
  Discipline: "History",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Vitaly",
  Discipline: "Biology",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Vitaly",
  Discipline: "Algebraic Topology",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Vitaly",
  Discipline: "Computer Sciences",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Vitaly",
  Discipline: "Tekhnical Analysis",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Vitaly",
  Discipline: "Introduction to shiting",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Vitaly",
  Discipline: "Introduction to pissing",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Vitaly",
  Discipline: "Shiting (advanced level)",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Vitaly",
  Discipline: "Pissing (advanced level)",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Vitaly",
  Discipline: "Speaking like a man",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Vitaly",
  Discipline: "Stealing money at parks",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Vitaly",
  Discipline: "Stealing money at streets",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Eugene",
  Discipline: "Analysis",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Eugene",
  Discipline: "Algebra",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Eugene",
  Discipline: "Geometry",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Eugene",
  Discipline: "Differential Equations",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Eugene",
  Discipline: "Topology",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Eugene",
  Discipline: "Irish Dance",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Eugene",
  Discipline: "Economics",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Eugene",
  Discipline: "English",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Eugene",
  Discipline: "Russian",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Eugene",
  Discipline: "Geography",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Eugene",
  Discipline: "Paleontology",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Eugene",
  Discipline: "History",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Eugene",
  Discipline: "Computer Sciences",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Eugene",
  Discipline: "Tekhnical Analysis",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Eugene",
  Discipline: "Introduction to shiting",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Eugene",
  Discipline: "Shiting (advanced level)",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Eugene",
  Discipline: "Pissing (advanced level)",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Eugene",
  Discipline: "Catching squirrels",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Eugene",
  Discipline: "Stealing money at streets",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Eugene",
  Discipline: "Krasnodaring",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Babeshko",
  Discipline: "Algebra",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Babeshko",
  Discipline: "Differential Equations",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Babeshko",
  Discipline: "Topology",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Babeshko",
  Discipline: "Economics",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Babeshko",
  Discipline: "Russian",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Babeshko",
  Discipline: "Art",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Babeshko",
  Discipline: "Geography",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Babeshko",
  Discipline: "Paleontology",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Babeshko",
  Discipline: "Biology",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Babeshko",
  Discipline: "Algebraic Topology",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Babeshko",
  Discipline: "Computer Sciences",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Babeshko",
  Discipline: "Tekhnical Analysis",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Babeshko",
  Discipline: "Shiting (advanced level)",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Babeshko",
  Discipline: "Pissing (advanced level)",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Babeshko",
  Discipline: "Street fighting",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Babeshko",
  Discipline: "Stealing money at parks",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Babeshko",
  Discipline: "Leaving in Ismailovo",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Marina Vadimovna",
  Discipline: "Analysis",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Marina Vadimovna",
  Discipline: "Algebra",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Marina Vadimovna",
  Discipline: "Geometry",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Marina Vadimovna",
  Discipline: "Topology",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Marina Vadimovna",
  Discipline: "Economics",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Marina Vadimovna",
  Discipline: "English",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Marina Vadimovna",
  Discipline: "Paleontology",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Marina Vadimovna",
  Discipline: "History",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Marina Vadimovna",
  Discipline: "Biology",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Marina Vadimovna",
  Discipline: "Computer Sciences",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Marina Vadimovna",
  Discipline: "Tekhnical Analysis",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Marina Vadimovna",
  Discipline: "Introduction to shiting",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Marina Vadimovna",
  Discipline: "Introduction to pissing",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Marina Vadimovna",
  Discipline: "Shiting (advanced level)",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Marina Vadimovna",
  Discipline: "Speaking like a man",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Marina Vadimovna",
  Discipline: "Stealing money at parks",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Marina Vadimovna",
  Discipline: "Stealing money at streets",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Marina Vadimovna",
  Discipline: "Krasnodaring",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Biryuk",
  Discipline: "Topology",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Biryuk",
  Discipline: "Economics",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Biryuk",
  Discipline: "Art",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Biryuk",
  Discipline: "Biology",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Biryuk",
  Discipline: "Algebraic Topology",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Biryuk",
  Discipline: "Tekhnical Analysis",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Biryuk",
  Discipline: "Introduction to pissing",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Biryuk",
  Discipline: "Shiting (advanced level)",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Biryuk",
  Discipline: "Speaking like a man",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Biryuk",
  Discipline: "Catching squirrels",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Biryuk",
  Discipline: "Stealing money at parks",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Biryuk",
  Discipline: "Stealing money at streets",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Biryuk",
  Discipline: "Krasnodaring",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Alladin",
  Discipline: "Analysis",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Alladin",
  Discipline: "Algebra",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Alladin",
  Discipline: "Geometry",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Alladin",
  Discipline: "Differential Equations",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Alladin",
  Discipline: "Irish Dance",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Alladin",
  Discipline: "Economics",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Alladin",
  Discipline: "English",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Alladin",
  Discipline: "Art",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Alladin",
  Discipline: "Geography",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Alladin",
  Discipline: "Paleontology",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Alladin",
  Discipline: "Algebraic Topology",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Alladin",
  Discipline: "Computer Sciences",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Alladin",
  Discipline: "Introduction to shiting",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Alladin",
  Discipline: "Introduction to pissing",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Alladin",
  Discipline: "Speaking like a man",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Alladin",
  Discipline: "Stealing money at parks",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Alladin",
  Discipline: "Stealing money at streets",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Alladin",
  Discipline: "Leaving in Ismailovo",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Alladin",
  Discipline: "Krasnodaring",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Galya",
  Discipline: "Analysis",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Galya",
  Discipline: "Geometry",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Galya",
  Discipline: "Differential Equations",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Galya",
  Discipline: "Irish Dance",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Galya",
  Discipline: "Economics",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Galya",
  Discipline: "English",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Galya",
  Discipline: "Russian",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Galya",
  Discipline: "Art",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Galya",
  Discipline: "Geography",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Galya",
  Discipline: "Paleontology",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Galya",
  Discipline: "History",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Galya",
  Discipline: "Biology",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Galya",
  Discipline: "Computer Sciences",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Galya",
  Discipline: "Tekhnical Analysis",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Galya",
  Discipline: "Introduction to shiting",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Galya",
  Discipline: "Shiting (advanced level)",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Galya",
  Discipline: "Pissing (advanced level)",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Galya",
  Discipline: "Speaking like a man",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Galya",
  Discipline: "Street fighting",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Galya",
  Discipline: "Stealing money at streets",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Galya",
  Discipline: "Leaving in Ismailovo",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Galya",
  Discipline: "Krasnodaring",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Davidyan",
  Discipline: "Analysis",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Davidyan",
  Discipline: "Differential Equations",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Davidyan",
  Discipline: "Irish Dance",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Davidyan",
  Discipline: "Economics",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Davidyan",
  Discipline: "English",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Davidyan",
  Discipline: "Russian",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Davidyan",
  Discipline: "Art",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Davidyan",
  Discipline: "Geography",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Davidyan",
  Discipline: "Paleontology",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Davidyan",
  Discipline: "History",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Davidyan",
  Discipline: "Biology",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Davidyan",
  Discipline: "Algebraic Topology",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Davidyan",
  Discipline: "Computer Sciences",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Davidyan",
  Discipline: "Tekhnical Analysis",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Davidyan",
  Discipline: "Introduction to pissing",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Davidyan",
  Discipline: "Shiting (advanced level)",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Davidyan",
  Discipline: "Pissing (advanced level)",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Davidyan",
  Discipline: "Speaking like a man",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Davidyan",
  Discipline: "Street fighting",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Davidyan",
  Discipline: "Stealing money at parks",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Davidyan",
  Discipline: "Stealing money at streets",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Pirson",
  Discipline: "Analysis",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Pirson",
  Discipline: "Algebra",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Pirson",
  Discipline: "Geometry",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Pirson",
  Discipline: "Differential Equations",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Pirson",
  Discipline: "Topology",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Pirson",
  Discipline: "Economics",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Pirson",
  Discipline: "English",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Pirson",
  Discipline: "Art",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Pirson",
  Discipline: "Geography",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Pirson",
  Discipline: "Paleontology",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Pirson",
  Discipline: "History",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Pirson",
  Discipline: "Biology",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Pirson",
  Discipline: "Algebraic Topology",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Pirson",
  Discipline: "Computer Sciences",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Pirson",
  Discipline: "Introduction to shiting",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Pirson",
  Discipline: "Introduction to pissing",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Pirson",
  Discipline: "Street fighting",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Pirson",
  Discipline: "Stealing money at parks",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Pirson",
  Discipline: "Stealing money at streets",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Pirson",
  Discipline: "Leaving in Ismailovo",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Pirson",
  Discipline: "Krasnodaring",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Gauss",
  Discipline: "Analysis",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Gauss",
  Discipline: "Algebra",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Gauss",
  Discipline: "Topology",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Gauss",
  Discipline: "Irish Dance",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Gauss",
  Discipline: "Economics",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Gauss",
  Discipline: "Russian",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Gauss",
  Discipline: "Geography",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Gauss",
  Discipline: "Paleontology",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Gauss",
  Discipline: "History",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Gauss",
  Discipline: "Algebraic Topology",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Gauss",
  Discipline: "Tekhnical Analysis",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Gauss",
  Discipline: "Introduction to pissing",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Gauss",
  Discipline: "Shiting (advanced level)",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Gauss",
  Discipline: "Pissing (advanced level)",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Gauss",
  Discipline: "Speaking like a man",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Gauss",
  Discipline: "Catching squirrels",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Gauss",
  Discipline: "Stealing money at streets",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Gauss",
  Discipline: "Leaving in Ismailovo",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Zorich",
  Discipline: "Analysis",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Zorich",
  Discipline: "Geometry",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Zorich",
  Discipline: "Differential Equations",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Zorich",
  Discipline: "Topology",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Zorich",
  Discipline: "Irish Dance",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Zorich",
  Discipline: "Economics",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Zorich",
  Discipline: "English",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Zorich",
  Discipline: "Geography",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Zorich",
  Discipline: "Paleontology",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Zorich",
  Discipline: "History",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Zorich",
  Discipline: "Biology",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Zorich",
  Discipline: "Algebraic Topology",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Zorich",
  Discipline: "Computer Sciences",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Zorich",
  Discipline: "Introduction to pissing",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Zorich",
  Discipline: "Pissing (advanced level)",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Zorich",
  Discipline: "Speaking like a man",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Zorich",
  Discipline: "Street fighting",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Zorich",
  Discipline: "Catching squirrels",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Zorich",
  Discipline: "Stealing money at parks",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Zorich",
  Discipline: "Leaving in Ismailovo",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Michaella",
  Discipline: "Analysis",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Michaella",
  Discipline: "Geometry",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Michaella",
  Discipline: "Differential Equations",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Michaella",
  Discipline: "Topology",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Michaella",
  Discipline: "Irish Dance",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Michaella",
  Discipline: "Russian",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Michaella",
  Discipline: "Art",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Michaella",
  Discipline: "Geography",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Michaella",
  Discipline: "Paleontology",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Michaella",
  Discipline: "History",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Michaella",
  Discipline: "Biology",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Michaella",
  Discipline: "Algebraic Topology",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Michaella",
  Discipline: "Computer Sciences",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Michaella",
  Discipline: "Introduction to shiting",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Michaella",
  Discipline: "Introduction to pissing",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Michaella",
  Discipline: "Shiting (advanced level)",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Michaella",
  Discipline: "Street fighting",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Michaella",
  Discipline: "Stealing money at parks",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Michaella",
  Discipline: "Stealing money at streets",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Michaella",
  Discipline: "Leaving in Ismailovo",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Michaella",
  Discipline: "Krasnodaring",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Vinogradov",
  Discipline: "Analysis",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Vinogradov",
  Discipline: "Algebra",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Vinogradov",
  Discipline: "Geometry",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Vinogradov",
  Discipline: "Irish Dance",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Vinogradov",
  Discipline: "Economics",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Vinogradov",
  Discipline: "Paleontology",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Vinogradov",
  Discipline: "Algebraic Topology",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Vinogradov",
  Discipline: "Introduction to pissing",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Vinogradov",
  Discipline: "Shiting (advanced level)",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Vinogradov",
  Discipline: "Pissing (advanced level)",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Vinogradov",
  Discipline: "Speaking like a man",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Vinogradov",
  Discipline: "Street fighting",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Vinogradov",
  Discipline: "Stealing money at parks",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Vinogradov",
  Discipline: "Stealing money at streets",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Vinogradov",
  Discipline: "Krasnodaring",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Titov",
  Discipline: "Analysis",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Titov",
  Discipline: "Algebra",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Titov",
  Discipline: "Geometry",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Titov",
  Discipline: "Topology",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Titov",
  Discipline: "Irish Dance",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Titov",
  Discipline: "English",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Titov",
  Discipline: "Art",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Titov",
  Discipline: "Geography",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Titov",
  Discipline: "Paleontology",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Titov",
  Discipline: "Biology",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Titov",
  Discipline: "Tekhnical Analysis",
  Mark: 3,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Titov",
  Discipline: "Introduction to pissing",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Titov",
  Discipline: "Shiting (advanced level)",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Titov",
  Discipline: "Pissing (advanced level)",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
},
{
  Name: "Titov",
  Discipline: "Speaking like a man",
  Mark: 2,
  Passed: false,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: true,
},
{
  Name: "Titov",
  Discipline: "Stealing money at parks",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: true,
},
{
  Name: "Titov",
  Discipline: "Stealing money at streets",
  Mark: 4,
  Passed: true,
  PissHimselfAtExam: true,
  ShitHimselfAtExam: false,
},
{
  Name: "Titov",
  Discipline: "Leaving in Ismailovo",
  Mark: 5,
  Passed: true,
  PissHimselfAtExam: false,
  ShitHimselfAtExam: false,
}
];